#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor -g 1920x1080+0+0
bspc monitor -d 1 2 3 4 5

# BSPWM behaviour
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true

# BSPWM Aesthetics
bspc config border_width			3
bspc config window_gap				14
bspc config normal_border_color		"#3F3F3F"
bspc config focused_border_color	"#f4b8e4"

# BSPWM rules
bspc rule -a Yad state=floating

#Autostart
fcitx -d
xsetroot -cursor_name left_ptr
feh --bg-center ~/.config/bspwm/wallpapers/58023966_p0_waifu2x_noise1_scale2x.png
#picom --experimental-backend
polybar -q workspace &
polybar -q launch &
polybar -q power &
polybar -q date &
polybar -q vol &
polybar -q spotify &
