#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor -d 1 2 3 4 5

# BSPWM behaviour
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true
bspc config left_padding			50

# BSPWM Aesthetics
bspc config border_width			2
bspc config window_gap				12
bspc config normal_border_color		"#3F3F3F"
bspc config focused_border_color	"#7FB4CA"

# BSPWM rules


#Autostart
fcitx -d
xsetroot -cursor_name left_ptr


