#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
#bspc monitor -g 1920x1080+0+0
xrandr --output DVI-D-0 --primary --mode 1920x1080 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --left-of DVI-D-0
bspc wm -O DVI-D-0 HDMI-0 
bspc monitor DVI-D-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 0

# BSPWM behaviour
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true

# BSPWM Aesthetics
bspc config border_width			3
bspc config window_gap				14
bspc config normal_border_color		"#3F3F3F"
bspc config focused_border_color	"#f4b8e4"

# BSPWM rules
bspc rule -a Yad state=floating

#Autostart
fcitx -d
xsetroot -cursor_name left_ptr
nm-applet &
feh --bg-center $HOME/.config/bspwm/wallpapers/58023966_p0.png
picom --experimental-backend &
$HOME/.config/polybar/scripts/launch.sh
sleep 1
$HOME/.config/polybar/scripts/launch.sh

